---
title: "Package Usage"
author: "Xianghui Dong"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Package Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Intro
- how to use package functions in analysis.
- Since most functions belong to a workflow, it's easier to put all functions usage examples in a workflow example than giving individual code examples in function help.
- test code, write document individually, but not to knit document in building site until final version.

```{r libraries and data, eval=FALSE}
library(ctmm)
library(ctmmweb)
data(buffalo)
```

```{r basic data structure, eval=FALSE}
merge_tele(buffalo)
```

```{r plot location and time, eval=FALSE}

dt <- merge_tele(buffalo)$data
selected_dt <- dt[identity %in% c("Gabs", "Queen")]
plot_loc(selected_dt, dt)
plot_loc_facet(selected_dt)
plot_time(selected_dt)
# you can take the ggplot2 object to further customize it
plot_loc(selected_dt, dt) +
  ggplot2::ggtitle("Locations of Buffalos") +
  # override the default left alignment of title and make it bigger
  ctmmweb:::CENTER_TITLE
# or export plot as png
g <- plot_loc(selected_dt, dt)
ggplot2::ggsave("test.png", g)
```

```{r model summary, eval=FALSE}
sample_tele(buffalo[[1]], 100)
data_sample <- sample_tele_list(buffalo, 100)
model_fit_res <- par_fit_tele(data_sample)
summary_model_fit(model_fit_res)
```

```{r parallel, eval=FALSE}
par_fit_tele(sample_tele_list(buffalo, 100))

# para_ll_ud(align_list(buffalo, models_list))
```

```{r variogram, eval=FALSE}

```

